function q_d = f_red(q,u)
global mp J0 Jp Larm lp g bma bp Kt Ke Rm eta_g Kg
%F_RED
%    q_d = f_red(in1,V,mp,J0,Jp,Larm,lp,g,bma,bp,Kt,Ke,Rm,eta_g,Kg)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    09-Dec-2019 19:45:31

al_d = q(3);
th = q(2);
th_d = q(4);
q_d = [al_d;th_d;((Jp.*al_d.*bma.*2.0+Jp.^2.*al_d.*th_d.*sin(th.*2.0).*2.0-Larm.*bp.*lp.*mp.*th_d.*cos(th).*2.0+Larm.*g.*lp.^2.*mp.^2.*cos(th).*sin(th).*2.0-(Jp.*Kg.*Kt.*eta_g.*(u-Ke.*Kg.*al_d).*2.0)./Rm-Jp.*Larm.*lp.*mp.*th_d.^2.*sin(th).*2.0+Jp.*Larm.*al_d.^2.*lp.*mp.*sin(th.*2.0).*cos(th)).*(-1.0./2.0))./(Jp.^2.*sin(th).^2+J0.*Jp-Larm.^2.*lp.^2.*mp.^2.*cos(th).^2);(J0.*bp.*th_d.*-2.0+Jp.^2.*al_d.^2.*sin(th.*2.0).*sin(th).^2-Jp.*bp.*th_d.*sin(th).^2.*2.0+J0.*Jp.*al_d.^2.*sin(th.*2.0)+Jp.*g.*lp.*mp.*sin(th).^3.*2.0+J0.*g.*lp.*mp.*sin(th).*2.0+Larm.*al_d.*bma.*lp.*mp.*cos(th).*2.0-Larm.^2.*lp.^2.*mp.^2.*th_d.^2.*cos(th).*sin(th).*2.0+Jp.*Larm.*al_d.*lp.*mp.*th_d.*sin(th.*2.0).*cos(th).*2.0-(Kg.*Kt.*Larm.*eta_g.*lp.*mp.*cos(th).*(u-Ke.*Kg.*al_d).*2.0)./Rm)./(Jp.^2.*sin(th).^2.*2.0+J0.*Jp.*2.0-Larm.^2.*lp.^2.*mp.^2.*cos(th).^2.*2.0)];
